module.exports = {
    optimizeDeps: {
        include: [
            'lodash.get',
            'lodash.has',
            'lodash.assign',
            'lodash.camelcase',
            'lodash.clonedeep',
            'lodash.compact',
            'lodash.find',
            'lodash.flatten',
            'lodash.forin',
            'lodash.get',
            'lodash.has',
            'lodash.invokemap',
            'lodash.isempty',
            'lodash.isequal',
            'lodash.isfunction',
            'lodash.isinteger',
            'lodash.isplainobject',
            'lodash.lowerfirst',
            'lodash.map',
            'lodash.mapvalues',
            'lodash.pick',
            'lodash.snakecase',
            'lodash.uniq',
            'lodash.uniqby',
            'lodash.values',
        ],
    },
};
